# Generated by Django 4.2.7 on 2025-10-22 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True)),
                ("po_number", models.CharField(db_index=True, max_length=100)),
                ("po_line_no", models.CharField(max_length=50)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("site_name", models.CharField(blank=True, max_length=255, null=True)),
                ("site_code", models.CharField(blank=True, max_length=100, null=True)),
                ("item_code", models.CharField(blank=True, max_length=100, null=True)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("item_description_local", models.TextField(blank=True, null=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("requested_qty", models.IntegerField(blank=True, null=True)),
                ("due_qty", models.IntegerField(blank=True, null=True)),
                ("billed_qty", models.IntegerField(blank=True, null=True)),
                ("quantity_cancel", models.IntegerField(blank=True, null=True)),
                (
                    "line_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "tax_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("po_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_method",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("customer", models.CharField(blank=True, max_length=255, null=True)),
                ("rep_office", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subcontract_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("pr_no", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sales_contract_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("version_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "shipment_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "engineering_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "engineering_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "subproject_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "center_area",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "product_category",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bidding_area",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("bill_to", models.TextField(blank=True, null=True)),
                ("ship_to", models.TextField(blank=True, null=True)),
                ("note_to_receiver", models.TextField(blank=True, null=True)),
                ("ff_buyer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "fob_lookup_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("publish_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("expire_date", models.DateField(blank=True, null=True)),
                ("acceptance_date", models.DateField(blank=True, null=True)),
                ("acceptance_date_1", models.DateField(blank=True, null=True)),
                ("change_history", models.TextField(blank=True, null=True)),
                ("pr_po_automation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "purchase_orders",
                "indexes": [
                    models.Index(fields=["user", "batch_id"], name="idx_po_user_batch"),
                    models.Index(
                        fields=["user", "po_number", "po_line_no"], name="idx_po_lookup"
                    ),
                ],
                "unique_together": {("user", "po_number", "po_line_no", "batch_id")},
            },
        ),
        migrations.CreateModel(
            name="Acceptance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("batch_id", models.UUIDField(db_index=True)),
                ("acceptance_no", models.CharField(max_length=100)),
                ("po_number", models.CharField(db_index=True, max_length=100)),
                ("po_line_no", models.CharField(max_length=50)),
                (
                    "shipment_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "milestone_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "project_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("site_name", models.CharField(blank=True, max_length=255, null=True)),
                ("site_code", models.CharField(blank=True, max_length=100, null=True)),
                ("acceptance_description", models.TextField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50, null=True)),
                ("currency", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "bill_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "accepted_qty",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "center_area",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("planned_completion_date", models.DateField(blank=True, null=True)),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("application_submitted", models.DateField(blank=True, null=True)),
                ("application_processed", models.DateField(blank=True, null=True)),
                ("approver", models.CharField(blank=True, max_length=255, null=True)),
                ("current_handler", models.TextField(blank=True, null=True)),
                (
                    "approval_progress",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "isdp_project",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("header_remarks", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "service_code",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "payment_percentage",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "record_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "acceptances",
                "indexes": [
                    models.Index(
                        fields=["user", "batch_id"], name="idx_acc_user_batch"
                    ),
                    models.Index(
                        fields=["user", "po_number", "po_line_no"],
                        name="idx_acc_lookup",
                    ),
                ],
                "unique_together": {
                    ("user", "acceptance_no", "po_number", "po_line_no", "batch_id")
                },
            },
        ),
    ]
