# Generated by Django 4.2.7 on 2025-10-22 10:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("external_pos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="externalpo",
            name="idx_external_po_status",
        ),
        migrations.RenameIndex(
            model_name="externalpo",
            new_name="idx_ext_po_sbc",
            old_name="idx_external_po_sbc",
        ),
        migrations.AlterField(
            model_name="externalpo",
            name="assigned_to_sbc",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_external_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="externalpo",
            name="assignment_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externalpo",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_external_pos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="externalpo",
            name="internal_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="externalpo",
            name="internal_po_id",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="externalpo",
            name="po_lines_data",
            field=models.JSONField(
                help_text="Array of objects: [{po_id, po_number, po_line}, ...]"
            ),
        ),
        migrations.AlterField(
            model_name="externalpo",
            name="po_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                help_text="Array of PO numbers",
                size=None,
            ),
        ),
        migrations.AddIndex(
            model_name="externalpo",
            index=models.Index(
                fields=["status", "created_at"], name="idx_ext_po_status"
            ),
        ),
    ]
